.github/workflows/docker-build-publish-prod.yml

---
Fixed the github action flow, change the username of ghcr.io to github actor.

Action: change to github actor

---

.github/workflows/docker-build-publish-prod.yml

**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**
---
Add github package permissions.

Action: github package permissions

---

.github/workflows/docker-build-publish-prod.yml
apps/cloud/src/app/@core/interceptors/api.interceptor.ts
apps/cloud/src/app/@core/providers/index.ts
apps/cloud/src/app/@core/providers/url.ts
apps/cloud/src/app/@core/services/chat.service.ts
apps/cloud/src/app/@core/services/xpert-agent.service.ts
apps/cloud/src/app/@core/services/xpert.service.ts
apps/cloud/src/app/features/xpert/studio/panel/preview/preview.component.html
apps/cloud/src/app/features/xpert/studio/panel/preview/preview.component.ts
apps/cloud/src/assets/i18n/zh-Hans.json
apps/cloud/src/assets/i18n/zh-Hant.json
packages/copilot-angular/src/lib/chat/chat.component.ts
packages/server-ai/src/copilot-provider/dto/copilot-provider-public.dto.ts
packages/server-ai/src/copilot/copilot.service.ts

---
1. Fixed the api base url for chat.
2. filter disabled copilots of tenant.

Fixed: api base url for chat apis

---

apps/cloud/src/app/features/chat/component-message/component-message.component.html
apps/cloud/src/app/features/semantic-model/model/members/cube/cube.component.scss
libs/story-angular/widgets/kpi/kpi.component.html
packages/analytics/src/ai/toolset/builtin/chatbi/chatbi.ts
packages/analytics/src/chatbi/graph/prompts.ts
packages/server-ai/src/ai-model/model_providers/openai/text-embedding/text-embedding.ts
packages/server-ai/src/xpert-agent/commands/handlers/execute.handler.ts

---
feat: openai text embedding model & chatbi kpi component

feat: openai text embedding model & chatbi kpi component

---

apps/cloud/src/app/@core/services/fetch-event-source.ts

---
Fix: retry fetchEventSource when hidden then re-open browser tab.

fix: openWhenHidden for fetchEventSource

---

apps/cloud/src/app/@shared/copilot/prompt-editor/editor.component.ts
packages/server-ai/src/xpert-agent/queries/handlers/get-variables.handler.ts
packages/server-ai/src/xpert/queries/handlers/get-xpert-agent.handler.ts

---
1. Fixed bug in get agent variables api.

fix: get variables of agent

---

apps/cloud/src/app/@core/guards/dirty-check.guard.ts
apps/cloud/src/app/features/xpert/studio/studio.component.html
apps/cloud/src/app/features/xpert/studio/studio.component.scss
apps/cloud/src/app/features/xpert/studio/studio.component.ts
apps/cloud/src/app/features/xpert/tools/builtin/authorize/credential/credential.component.html
apps/cloud/src/app/features/xpert/tools/builtin/authorize/credential/credential.component.ts
apps/cloud/src/app/features/xpert/tools/builtin/configure/configure.component.html
apps/cloud/src/app/features/xpert/tools/builtin/configure/configure.component.ts
apps/cloud/src/app/features/xpert/tools/tool-test/test/tool.component.html
apps/cloud/src/app/features/xpert/tools/tool-test/test/tool.component.ts
apps/cloud/src/app/features/xpert/tools/xpert-tool-test/tool.component.ts
apps/cloud/src/app/features/xpert/workspace/xperts/xperts.component.ts
apps/cloud/src/app/features/xpert/xpert/basic/basic.component.ts
apps/cloud/src/app/features/xpert/xpert/routes.ts
packages/angular/common/remote-select/select.component.ts
packages/server-ai/src/integration-lark/lark.hooks.controller.ts
packages/server-ai/src/xpert-tool/xpert-tool.entity.ts
packages/server-ai/src/xpert-toolset/xpert-toolset.entity.ts
packages/server/src/i18n/en/integration.json
packages/server/src/i18n/zh/integration.json

1. Error message when config feishu message toolset.
2. Xpert studio styles.
---

Pre-release version 3.0.14

---

apps/cloud/src/app/xpert/home.service.ts
apps/cloud/src/app/xpert/home/home.component.html
apps/cloud/src/app/xpert/home/home.component.ts

fixed: ocap dependency for chat webapp
---

fix: ocap dependency for chat webapp

---

apps/cloud/src/app/features/chat/home.component.html
apps/cloud/src/app/features/chat/home.component.ts
apps/cloud/src/app/features/chat/tasks/tasks.component.html
apps/cloud/src/app/features/chat/xpert/xpert.component.html
apps/cloud/src/app/features/chat/xpert/xpert.component.ts
apps/cloud/src/app/features/xpert/explore/explore.component.html
apps/cloud/src/app/features/xpert/explore/explore.component.scss
apps/cloud/src/app/features/xpert/explore/explore.component.ts
apps/cloud/src/app/features/xpert/workspace/home/home.component.html
apps/cloud/src/app/features/xpert/workspace/home/home.component.scss
apps/cloud/src/app/features/xpert/workspace/home/home.component.ts
apps/cloud/src/app/xpert/component-message/tasks/tasks.component.html
apps/cloud/src/app/xpert/home/home.component.html
apps/cloud/src/app/xpert/home/home.component.ts
packages/server-ai/src/xpert-task/xpert-task.controller.ts
packages/server-ai/src/xpert-task/xpert-task.service.ts

Feat: tasks components in chat page.
---

feat: task component in chat

---

apps/cloud/src/app/@shared/copilot/copilot-provider-model/model.component.ts
apps/cloud/src/app/features/chat/chat.service.ts
apps/cloud/src/app/features/chat/xperts/xperts.component.ts
apps/cloud/src/app/xpert/conversation/conversation.component.html
packages/server-ai/src/xpert-task/xpert-task.controller.ts
packages/server-ai/src/xpert-task/xpert-task.entity.ts

Fixed: Expose temporary properties for task dto class.
Fixed: new xpert conversation.
---

Fixed: export properties for dto class

---

apps/cloud/src/app/@shared/chat/preview/preview.component.html
apps/cloud/src/app/@shared/chat/preview/preview.component.ts
apps/cloud/src/app/features/setting/copilot/basic/basic.component.ts
apps/cloud/src/app/features/setting/copilot/usages/usages.component.ts
apps/cloud/src/app/features/xpert/xpert/memory/memory.component.html
packages/server-ai/src/chat-conversation/commands/handlers/schedule-summary.handler.ts
packages/server-ai/src/chat-conversation/summary.job.ts
packages/server-ai/src/chat/chat.controller.ts
packages/server-ai/src/copilot-store/store.ts
packages/server-ai/src/xpert/commands/handlers/chat.handler.ts
packages/server-ai/src/xpert/queries/handlers/get-memory-embedding.handler.ts
packages/server/src/i18n/en/xpert.json
packages/server/src/i18n/zh/xpert.json

Fixed no embeddings model for long-term memory.
Fixes #36 
---

fixed: not configure embeddings model for xpert memory

---

.deploy/api/package-prod.json
.deploy/api/package.json
.deploy/webapp/package.json
package.json
packages/copilot-angular/package.json
packages/server-ai/package.json
packages/server-ai/src/copilot-knowledge/copilot-knowledge.service.ts
yarn.lock

fix: langchain version

---

apps/cloud/src/app/@core/services/xpert-task.service.ts
apps/cloud/src/app/@shared/chat/task-dialog/task-dialog.component.html
apps/cloud/src/app/@shared/chat/task-dialog/task-dialog.component.ts
apps/cloud/src/app/@shared/copilot/prompt-editor/editor.component.html
apps/cloud/src/app/@shared/xpert/variables-assigner/variables-assigner.component.html
apps/cloud/src/app/features/features-routing.module.ts
apps/cloud/src/app/features/features.component.ts
apps/cloud/src/app/features/xpert/explore/explore.component.ts
apps/cloud/src/app/features/xpert/explore/install/install.component.html
apps/cloud/src/app/features/xpert/explore/install/install.component.ts
apps/cloud/src/app/features/xpert/explore/routes.ts
apps/cloud/src/app/features/xpert/routes.ts
apps/cloud/src/app/features/xpert/workspace/home/home.component.ts
apps/cloud/src/app/features/xpert/xpert/basic/basic.component.html
apps/cloud/src/app/features/xpert/xpert/basic/basic.component.scss
apps/cloud/src/app/features/xpert/xpert/basic/basic.component.ts
apps/cloud/src/assets/i18n/zh-Hans.json
packages/server-ai/src/xpert-task/xpert-task.controller.ts
packages/server-ai/src/xpert-task/xpert-task.entity.ts
packages/server-ai/src/xpert-task/xpert-task.service.ts

Fix task cron time expression error
**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**
---

Fix task cron time expression error

---

apps/cloud/src/app/features/setting/chatbi/model/model.component.html
apps/cloud/src/app/features/setting/chatbi/model/model.component.ts
apps/cloud/src/app/features/setting/chatbi/models/models.component.html
apps/cloud/src/app/features/setting/chatbi/models/models.component.ts
apps/cloud/src/assets/i18n/zh-Hans.json
packages/angular/common/select/select/select.component.ts

Fixed If model is empty, an error is reported of ChatBI models configuration.
Fix #48 
---

fix: empty model error of chatbi models

---

apps/cloud/src/app/features/semantic-model/upload/upload.component.html
apps/cloud/src/app/features/semantic-model/upload/upload.component.scss
apps/cloud/src/assets/i18n/zh-Hans.json
packages/adapter/src/adapters/postgres/postgres.ts
packages/adapter/src/helpers.ts
packages/analytics/nodemon-debug.json
packages/analytics/nodemon.json
packages/analytics/src/data-source/utils.ts

fix: error when upload excel file in semantic model

---

packages/server-ai/src/xpert/commands/handlers/publish.handler.ts

fix: Agent 'Agent_XXXXX' record has been updated

---

apps/cloud/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.html
apps/cloud/src/app/@shared/invite/forms/email-invite-form/email-invite-form.component.ts
apps/cloud/src/app/@shared/invite/invite-mutation/invite-mutation.component.html
apps/cloud/src/app/@shared/user/forms/basic-info/basic-info-form.component.html
apps/cloud/src/app/@shared/user/forms/basic-info/basic-info-form.component.ts
apps/cloud/src/app/@shared/user/user-mutation/user-mutation.component.html
apps/cloud/src/app/@shared/user/user-mutation/user-mutation.component.scss
apps/cloud/src/app/features/setting/users/edit-user/edit-user.component.html
apps/cloud/src/app/features/setting/users/edit-user/edit-user.component.scss
apps/cloud/src/app/features/setting/users/edit-user/edit-user.component.ts
apps/cloud/src/app/features/setting/users/manage-user/manage-user.component.html
apps/cloud/src/app/features/setting/users/manage-user/manage-user.component.ts
apps/cloud/src/app/features/setting/users/organizations/organizations.component.html
apps/cloud/src/app/features/setting/users/organizations/organizations.component.ts
apps/cloud/src/app/features/setting/users/user-basic/user-basic.component.html
apps/cloud/src/app/features/setting/users/user-basic/user-basic.component.ts
apps/cloud/src/app/features/setting/users/users.component.ts
apps/cloud/src/assets/i18n/zh-Hans.json
libs/apps/state/src/lib/users.service.ts
libs/formly/input/input.type.html
libs/formly/select/select.type.html
libs/formly/select/select.type.ts
libs/formly/src/lib/providers.ts
packages/adapter/src/adapters/postgres/postgres.ts
packages/analytics/src/core/events/handlers/organization.demo.handler.ts
packages/analytics/src/core/seeds/seed-data.service.ts
packages/analytics/src/model/events/handlers/datasource-updated.handler.ts
packages/analytics/src/model/helper.ts
packages/analytics/src/model/model.service.ts
packages/contracts/src/analytics/semantic-model.ts

semantic model bug & upgrade user manage
---

fix: semantic model bug & upgrade user manage

---

packages/analytics/src/model/model.service.ts

fix: model bug
- [ ✅ ] Have you followed the [contributing guidelines](https://github.com/xpert-ai/xpert/blob/master/.github/CONTRIBUTING.md)?
- [ ✅ ] Have you explained what your changes do, and why they add value?
**Please note: we will close your PR without comment if you do not check the boxes above and provide ALL requested information.**
---

fix: model bug

---

apps/cloud/src/app/features/semantic-model/creation/creation.component.html
apps/cloud/src/app/features/semantic-model/creation/creation.component.ts
packages/analytics/src/model/model.service.ts
packages/angular/common/search/_search.component.scss
packages/angular/common/table/selection-table/selection-table.component.html
packages/angular/common/table/selection-table/selection-table.component.ts

fix: catalog of model is required
---

fix: catalog of model is required

---

packages/server/src/custom-smtp/dto/custom-smtp.query.dto.ts

Disable validation for custom smtp
---

fix: disable validation for custom smtp

---

apps/cloud/src/app/features/setting/users/organizations/organizations.component.html
apps/cloud/src/app/features/setting/users/organizations/organizations.component.ts
apps/cloud/src/app/features/xpert/knowledge/knowledgebase/documents/create/step-1/step.component.ts
apps/cloud/src/assets/i18n/zh-Hans.json
packages/core/src/lib/filter.spec.ts
packages/core/src/lib/filter.ts

Fix remove user from org.
Fix merge filters with parameter in ocap.
---

Release v3.1.1

---

docker/docker-compose.cn.yml
docker/docker-compose.yml

Fix add command of api container.
---

feat: add command for api

---

.deploy/api/Dockerfile
packages/server-ai/src/rag-web/commands/handlers/load.handler.ts

fix: install deps in docker image
---

fix: install deps in docker image

---

packages/server-ai/src/app.module.ts
packages/server-ai/src/integration-lark/commands/handlers/chat-xpert.handler.ts
packages/server-ai/src/integration-lark/conversation.service.ts
packages/server-ai/src/rag-web/commands/handlers/load.handler.ts
packages/server-ai/src/xpert-agent/commands/handlers/invoke.handler.ts

Fixes #70 
Fixed Cache for feishu itegration.
---

fix: cache ttl of chatbi feishu toolset

---

packages/server-ai/src/xpert-agent/commands/handlers/subgraph.handler.ts

feat: add debug for empty send

---

packages/olap/Dockerfile

fix Update olap docker file

---

.deploy/olap/Dockerfile

Fix olap version in docker image.
---

Fix olap version in docker

---

apps/api/src/plugin-config.ts
packages/analytics/nodemon-debug.json
packages/config/src/default-configuration.ts

fix is docker env

---

tools/scripts/build.mjs

Fix skip-nx-cache

---

apps/api/src/polyfills.ts
packages/analytics/src/polyfills.ts

fix polyfills type

---

apps/api/src/polyfills.ts

fix node-fetch import

---

packages/server-ai/src/ai-model/model_providers/openai_api_compatible/openai_api_compatible.ts
packages/server-ai/src/ai-model/model_providers/openai_api_compatible/text-embedding/text-embedding.ts
packages/server-ai/src/copilot-knowledge/copilot-knowledge.entity.ts
packages/server-ai/src/copilot-organization/copilot-organization.entity.ts
packages/server-ai/src/copilot-user/copilot-user.entity.ts

Add OAIAPICompatTextEmbeddingModel
---

feat: add OAIAPICompatTextEmbeddingModel

---

packages/adapter/src/adapters/mssql/mssql.ts

fix: catalog of mssql

---

packages/server-ai/src/integration-lark/auth/lark-token.strategy.ts

feat: encryptKey for lark app

---

.deploy/api/Dockerfile
yarn.lock

fix: pkce require error

---

.deploy/api/entrypoint.compose.sh
.deploy/api/entrypoint.prod.sh

- Fix volume permission of /srv/pangolin/public
---

fix: permission for /srv/pangolin/public

---

apps/cloud/src/app/features/semantic-model/model/query-lab/query/query.component.html
apps/cloud/src/app/features/semantic-model/model/query-lab/query/query.component.ts
apps/cloud/src/app/xpert/ai-message/ai-message.component.html
apps/cloud/src/assets/i18n/zh-Hans.json
docker/docker-compose.dev.yml
packages/adapter/src/adapters/clickhouse/clickhouse.ts
packages/adapter/src/adapters/clickhouse/types.ts
packages/adapter/src/helpers.ts
packages/adapter/src/index.ts
packages/common/src/utils/xlsx.ts

- Add import in clickhouse adapter.
- Query lab
---

Version 3.2.5

---

apps/cloud/src/app/features/xpert/studio/domain/xpert-api.service.ts
packages/contracts/src/ai/xpert.model.ts
packages/server-ai/src/xpert-agent/commands/handlers/subgraph.handler.ts
packages/server-ai/src/xpert-agent/workflow/create-workflow.command.ts

- Fixed all channels for workflow node in agent graph.
---

fix: all channels for workflow node

---

packages/server-ai/src/xpert-agent/dto/agent-public.dto.ts
packages/server-ai/src/xpert/dto/xpert-public.dto.ts

- Fixed parameters in agent dto.
---

fix: parameter of public agent dto

---

apps/cloud/src/app/features/xpert/studio/components/workflow/knowledge/knowledge.component.html
apps/cloud/src/app/features/xpert/studio/domain/xpert-api.service.ts
apps/cloud/src/app/features/xpert/studio/panel/toolset/toolset.component.ts
apps/cloud/src/app/features/xpert/studio/panel/workflow/knowledge/knowledge.component.html
apps/cloud/src/app/features/xpert/studio/panel/workflow/subflow/subflow.component.ts
apps/cloud/src/app/features/xpert/studio/panel/workflow/workflow-base.component.ts
apps/cloud/src/app/features/xpert/studio/panel/xpert-agent/agent.component.ts
packages/contracts/src/agent/utils.ts
packages/server-ai/src/xpert-agent/commands/handlers/subgraph.handler.ts
packages/server-ai/src/xpert-agent/workflow/subflow.ts
packages/server-ai/src/xpert/commands/handlers/chat.handler.ts

- Fix Subflow.
- Fix summarize title
---

fix: subflow & sumarize title

---

apps/cloud/src/app/@shared/copilot/prompt-editor/editor.component.ts
apps/cloud/src/app/@shared/copilot/prompt-generator/generator.component.ts
apps/cloud/src/app/@theme/header/about/about.component.html
apps/cloud/src/app/@theme/header/about/about.component.scss
apps/cloud/src/app/@theme/header/about/about.component.ts
apps/cloud/src/app/@theme/header/user/user.component.html
apps/cloud/src/app/@theme/header/user/user.component.ts
apps/cloud/src/app/features/services/copilot.service.ts
apps/cloud/src/app/features/xpert/studio/panel/workflow/knowledge/knowledge.component.html
apps/cloud/src/app/features/xpert/studio/panel/workflow/knowledge/knowledge.component.ts
apps/cloud/src/assets/i18n/zh-Hans.json
apps/cloud/src/environments/environment.prod.ts
apps/cloud/src/environments/environment.ts
apps/cloud/src/environments/types.ts
packages/copilot-angular/src/lib/core/models/index.ts
packages/copilot-angular/src/lib/services/copilot.service.ts
packages/server-ai/src/ai/ai.controller.ts

- About version.
- Prompt generator
---

Version 3.2.9

---

apps/cloud/src/app/features/xpert/studio/components/workflow/iterating/iterating.component.scss
packages/contracts/src/agent/utils.spec.ts
packages/contracts/src/agent/utils.ts
packages/server-ai/src/xpert-agent/commands/handlers/subgraph.handler.ts

fix: Graph branch channel bug

---

apps/cloud/src/app/@theme/header/workspace-selector/workspace-selector.component.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.
---
|    before  |  after    |
| ---- | ---- |
|  ![before](https://github.com/user-attachments/assets/345ceae7-2b6c-4b39-8dd3-eb22e921bb24) |    ![after](https://github.com/user-attachments/assets/15c9de8c-5c32-4e76- …

Fixes #140 Fix the page error issue when the ws variable is null

---

apps/cloud/src/app/@shared/avatar/emoji-avatar-editor/avatar-editor.component.html
apps/cloud/src/app/@shared/avatar/emoji-avatar-editor/avatar-editor.component.ts

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
> [!Tip]
> Close issue syntax: `Fixes #<issue number>` or `Resolves #<issue number>`, see [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) for more details.
---
| Before     |  After    |
| ---- | ---- |
|   ![before](https://github.com/user-attachments/assets/ef10d2fa-e821-4bad-892c-d150ea1dc634) |   ![after](https://github.com/user-attachments/assets/8a1103e2-5575-43e7- …

Fixes #142 Dragging pictures for upload does not take effect

---

apps/cloud/src/environments/types.ts

version 3.2.13

---

apps/cloud/src/app/features/chat/projects/projects.component.html
packages/contracts/src/ai/chat-message.model.ts
packages/server-ai/src/xpert-agent/agent.ts

Version 3.3.2

---

packages/angular/prism/prism.component.ts

fix: package import

---

packages/olap/pom.xml

- Fix mondrian dependency for olap
---

fix: mondrian dependency

---

apps/api/package.json
apps/cloud/package.json
apps/cloud/src/environments/types.ts
packages/adapter/package.json
packages/analytics/package.json
packages/angular/package.json
packages/auth/package.json
packages/common/package.json
packages/config/package.json
packages/contracts/package.json
packages/copilot-angular/package.json
packages/copilot/package.json
packages/core/package.json
packages/duckdb/package.json
packages/echarts/package.json
packages/olap/.dockerignore
packages/olap/.gitignore
packages/olap/run.sh
packages/server-ai/package.json
packages/server/package.json
packages/sql/package.json
packages/sql/src/lib/dimension.ts
packages/store/package.json
packages/xmla/package.json
yarn.lock

- Fix do not bracketing join statement for clickhouse
---

Fix donot bracketing join statement for clickhouse

---

docker/docker-compose.cn.yml
packages/server/src/bootstrap/i18next.ts

- fix: config of docker compose cn
---

fix: config of docker compose cn

---

.env.local
packages/analytics/package.json
packages/analytics/src/data-source/commands/list-tables.command.ts
packages/analytics/src/data-source/commands/query-schema.command.ts
packages/analytics/src/data-source/commands/query-sql.command.ts
packages/analytics/src/model/model.service.ts
packages/analytics/src/model/validators/cube.ts
packages/analytics/src/model/validators/dimension-usage.ts
packages/analytics/src/model/validators/dimension.ts
packages/analytics/src/model/validators/tables.ts
packages/core/src/lib/copilot/schemas/common.ts
packages/core/src/lib/copilot/schemas/cube.ts
packages/server-ai/src/xpert-toolset/xpert-toolset.service.ts
yarn.lock

- Add more validator for semantic model building.
---

feat: semantic model toolset

---

apps/api/package.json
apps/cloud/package.json
apps/cloud/src/environments/types.ts
packages/adapter/package.json
packages/analytics/package.json
packages/angular/package.json
packages/auth/package.json
packages/common/package.json
packages/config/package.json
packages/contracts/package.json
packages/contracts/src/ai/xpert.model.ts
packages/copilot-angular/package.json
packages/copilot/package.json
packages/core/package.json
packages/duckdb/package.json
packages/echarts/package.json
packages/server-ai/package.json
packages/server-ai/src/xpert-agent/commands/handlers/invoke.handler.ts
packages/server-ai/src/xpert/commands/handlers/import.handler.ts
packages/server/package.json
packages/sql/package.json
packages/store/package.json
packages/xmla/package.json

Version 3.5.5
